# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13X-wc_oAUNxFdM2kzXHPmDZp_YgyRIM_
"""



import pandas as pd
import re 
from gensim.models import Word2Vec

df = pd.read_csv("/content/resume_dataset.csv")

df['text'] = df['Category']+ " " + df['Resume']

for i in range(0, len(df)):
  df['text'].iloc[i] = df['text'].iloc[i].lower()
  df['text'].iloc[i] = re.split('[0-9].|, |_|-|!|\r|\n| ', df['text'].iloc[i])
  df['text'].iloc[i] = [j for j in df['text'].iloc[i] if j]

sent = df['text'].tolist()

sent

model = Word2Vec(sent, min_count=1,size= 50,workers=3, window =3, sg = 1)

words = list(model.wv.vocab)

model.wv.most_similar('java')[:8]

model.save("recommend.model")

model = Word2Vec.load("recommend.model")